### ISSUE TITLE
Live collector source

### ISSUE THREAD

**Issue by kevinvalk** [flyersa/MuninMX#1]
Am I correct that you did not release the source code for the live collector? Or do you have some magic build rules to build the live collector from the daemon collector?

**Comment by flyersa** [comment]
Hi,

i think right now that was not released yes. Sorry will publish it asap. 
Its just a basic version of the mld.

Am 18.10.2015 um 01:07 schrieb Kevin Valk:
>
> Am I correct that you did not release the source code for the live 
> collector? Or do you have some magic build rules to build the live 
> collector from the daemon collector?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/flyersa/MuninMX/issues/1>.
>

-- 
Clavain Technologies
Enrico Kern

Heerstraße 366
13593 Berlin

GERMANY

WEB: http://www.clavain.com
TEL: +49 (30) 54818753
FAX: +49 (180) 5233633-548
